name: TypeScript types lint

on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "**.tsx"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - ".eslintignore"
      - ".github/workflows/eslint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.ts"
      - "**.tsx"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - ".eslintignore"
      - ".github/workflows/eslint.yml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pnpm cache
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-${{ hashFiles('**/.package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
          run_install: true

      - name: Run TypeScript
        run: pnpm run lint:types
